### ISSUE TITLE
Explicit requires missing

### ISSUE THREAD

**Issue by moolitayer** [ManageIQ/manageiq-providers-kubernetes#86]
We should require everything explicitly and not relay on auto loading.
include_concern is an alternative for require & include.

@cben can you please add the link where you explained about include_concern.

**Comment by cben** [comment]
manageiq has [`include_concern`][1] shortcut to DRY require_nested + include.
[`require_nested`][2] is also a manageiq extension.
I'm not sure if they're always equivalent; my understanding is that these strive to delay loading as much as possible, but do it "correctly" (with some [complex code to ensure correct .descendants for STI][3]), so we shouldn't care.

BTW, `require_nested` does `require_dependency`, not just `require`.  It's better than `require` because it tells Rails how to *reload* (in dev).

Ruby consts are hard :-(  Auto[re]loading is hard :-(  http://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html

[1]: https://github.com/ManageIQ/manageiq/blob/master/lib/extensions/as_include_concern.rb
[2]: https://github.com/ManageIQ/manageiq/blob/master/lib/extensions/require_nested.rb
[3]: https://github.com/ManageIQ/manageiq/blob/master/lib/extensions/descendant_loader.rb

P.S. I was claiming we have autoloading off in production, I was wrong.  AFAICT all 3 envs use autoloading, we disable eager loading.

**Comment by cben** [comment]
@moolitayer are you aware of specific places we miss requires?  An automatic way to find them?

**Comment by agrare** [comment]
To prevent loading more gems than required and to keep memory down we delay load dependencies so this is intentional.
